-- Lista obsugiwanych typów w PL/SQL jest dostępna na przykad na:
-- https://www.techonthenet.com/oracle/datatypes.php
-- Są tam również opisane w tabeli ich podstawowe specyfikacje

-- POWTÓRECZKA - ZAPIS ZMIENNA => INNAZMIENNA OZNZCZA ŻE ZMIENNA DĄŻY
-- DO DAEJ WARTOŚCI, TO TZW. KROKI.

-- WLĄCZENIE UOTPUT NA ZERVERZE TRZEBA WYKONAĆ KAŻDORAZOWO DLA KOŻDEJ SESJI:
SET SERVEROUTPUT ON;

Begin
exe_tekst('INITCAP');
end;

-- w tym przypadku dziala, ale gdy baz się wywala czasem może pomóc zastosowanie
-- starszedo rodzaju wywoania CALL.
-- OBECNIE RACZEJ NIE UŻYWANE, ALE MOŻE SIĘ pRZYDAĆ

CALL; EXE_TEKST('INTCAP');
SELECT * FROM OSOBY;

-- Programując w PL/SQL żadko kiedy kożystamy z kodu innych, zazwyczaj tworzymy
-- rzeczy których po prostu nie ma, jednak potrzebują one być używane przez
-- np administratorów i niezbędne jest komunikowanie blędów. dlatego trzeba
-- je również zaprogramować.

CREATE OR REPLACE procedure CZY_JEST
(NUM IN NUMBER , STATUS OUT NUMBER)
IS
KTO NUMBER;
BEGIN
SELECT IDOSOBY INTO KTO
FROM OSOBY WHERE IDOSOBY = NUM;
IF (KTO = NUM) THEN
STATUS:=1;
DBMS_OUTPUT.PUT_LINE('PRACOWNIK ISTNIEJE');
END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN
STATUS := 0;
DBMS_OUTPUT.PUT_LINE('PRACOWNIK NIE ISTNIEJE');
WHEN OTHERS THEN
NULL;
END;

-- FUNKCJA ZLICZAJĄCA REKRDY SPOWODUJE, ŻE JEŚLI PRACOWNIE O DANYM NUMERZE
-- ISTNIEJE, TO ZOSTANIE POLICZONY 1 REKORD, A JEŚLI NIE ISTNIEJE - O REKORDÓW:

CREATE OR REPLACE procedure CZY_JEST
(NUM IN NUMBER , STATUS OUT NUMBER , OK OUT NUMBER)
IS
BEGIN
OK:=0;
SELECT COUNT(IDOSOBY) INTO STATUS
FROM OSOBY WHERE IDOSOBY = NUM;
IF (STATUS = 1) THEN
DBMS_OUTPUT.PUT_LINE('PRACOWNIK ISTNIEJE');
ELSE
DBMS_OUTPUT.PUT_LINE('PRACOWNIK NIE ISTNIEJE');
END IF;
EXCEPTION
WHEN OTHERS THEN
OK := 99;
DBMS_OUTPUT.PUT_LINE('BLAD PRZETWARZANIA');
END;

-- FORMALNA MOŻLIWOŚĆ OBSUŻENIA DWÓCH LUB WIĘCEJ WYJ ĄTKÓW W TYM
-- SAMYM MIEJSCU SEKCJI ICH OBSUGI. W TYM CELU MOŻNA UŻYC KOLEJNYCH NAZW
-- WBUDOWANYCH W ŚRODOWISKO ORACLE

CREATE OR REPLACE procedure CZY_JEST
(NUM IN NUMBER , STATUS OUT NUMBER , OK OUT NUMBER)
IS
BEGIN
OK:=0;
SELECT COUNT(IDOSOBY) INTO STATUS
FROM OSOBY WHERE IDOSOBY = NUM;
IF (STATUS = 1) THEN
DBMS_OUTPUT.PUT_LINE('PRACOWNIK ISTNIEJE');
ELSE
DBMS_OUTPUT.PUT_LINE('PRACOWNIK NIE ISTNIEJE');
END IF;
EXCEPTION
WHEN INVALID_NUMBER OR NO_DATA_FOUND THEN
OK := 11;
DBMS_OUTPUT.PUT_LINE('BLAD WARTOŚCI');
WHEN OTHERS THEN
OK := 99;
DBMS_OUTPUT.PUT_LINE('BLAD PRZETWARZANIA');
END;


-- KOD POKAZUJĄCY ŻE NIE MA OSÓB O WZROŚCIE
-- WYŻSZYM OD PROGU DANEGO PARAMETREM

-- RAISE; OZNACZA WYŚWIETLENIE NA EKRANIE

CREATE OR REPLACE PROCEDURE LICZ
(MINI NUMBER, ILE UOT NUMBER)
IS
BRAKUJE EXCEPTION;
BEGIN
SELECT COUNT...
